# Generated by Django 4.0.1 on 2024-08-13 21:01

from django.db import migrations, models
import djongo.models.fields
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('_id', web.models.ObjectIdField(default=None, max_length=24, primary_key=True, serialize=False)),
                ('queue_len', models.IntegerField(blank=True, default=None, null=True)),
                ('most_credit', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cycling',
            fields=[
                ('_id', web.models.ObjectIdField(default=None, max_length=24, primary_key=True, serialize=False)),
                ('from_location', models.CharField(max_length=100, null=True)),
                ('to_location', models.CharField(max_length=100, null=True)),
                ('mode', models.CharField(max_length=50, null=True)),
                ('time', models.CharField(max_length=50, null=True)),
                ('distance', models.FloatField(null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distances',
            fields=[
                ('_id', web.models.ObjectIdField(default=None, max_length=24, primary_key=True, serialize=False)),
                ('transit', djongo.models.fields.EmbeddedField(blank=True, model_container=web.models.Transit, null=True)),
                ('cycling', djongo.models.fields.EmbeddedField(blank=True, model_container=web.models.Cycling, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('_id', web.models.ObjectIdField(default=None, max_length=24, primary_key=True, serialize=False)),
                ('from_location', models.CharField(max_length=100, null=True)),
                ('to_location', models.CharField(max_length=100, null=True)),
                ('mode', models.CharField(max_length=50, null=True)),
                ('time', models.CharField(max_length=50, null=True)),
                ('distance', models.FloatField(null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
