# Generated by Django 4.0.1 on 2024-08-06 18:55

from django.db import migrations, models
import djongo.models.fields
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('_id', web.models.ObjectIdField(default=None, max_length=24, primary_key=True, serialize=False)),
                ('queue_len', models.IntegerField(blank=True, default=None, null=True)),
                ('most_credit', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cycling',
            fields=[
                ('_id', web.models.ObjectIdField(default=None, max_length=24, primary_key=True, serialize=False)),
                ('from_location', models.CharField(max_length=100, null=True)),
                ('to_location', models.CharField(max_length=100, null=True)),
                ('mode', models.CharField(max_length=50, null=True)),
                ('time', models.CharField(max_length=50, null=True)),
                ('distance', models.FloatField(null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distances',
            fields=[
                ('_id', web.models.ObjectIdField(default=None, max_length=24, primary_key=True, serialize=False)),
                ('transit', djongo.models.fields.EmbeddedField(blank=True, model_container=web.models.Transit, null=True)),
                ('cycling', djongo.models.fields.EmbeddedField(blank=True, model_container=web.models.Cycling, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('_id', web.models.ObjectIdField(default=None, max_length=24, primary_key=True, serialize=False)),
                ('from_location', models.CharField(max_length=100, null=True)),
                ('to_location', models.CharField(max_length=100, null=True)),
                ('mode', models.CharField(max_length=50, null=True)),
                ('time', models.CharField(max_length=50, null=True)),
                ('distance', models.FloatField(null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApartmentAmount',
            fields=[
                ('_id', web.models.ObjectIdField(default=None, max_length=24, primary_key=True, serialize=False)),
                ('update_time', web.models.StringDateTimeField(blank=True, default=None, null=True)),
                ('amount', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'apartment_amount',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApartmentInfo',
            fields=[
                ('_id', web.models.ObjectIdField(default=None, max_length=24, primary_key=True, serialize=False)),
                ('update_time', web.models.StringDateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('object_number', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('housing_area', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('accommodation_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('floor', models.IntegerField(blank=True, default=None, null=True)),
                ('living_space', models.IntegerField(blank=True, default=None, null=True)),
                ('monthly_rent', models.IntegerField(blank=True, default=None, null=True)),
                ('valid_from', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('floor_drawing', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('apartment_drawing', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('application_ddl', web.models.StringDateTimeField(blank=True, default=None, null=True)),
                ('electricity_include', models.BooleanField(blank=True, default=None, null=True)),
                ('rent_free_june_and_july', models.BooleanField(blank=True, default=None, null=True)),
                ('max_4_years', models.BooleanField(blank=True, default=None, null=True)),
                ('bid', djongo.models.fields.EmbeddedField(blank=True, default=None, model_container=web.models.Bid, null=True)),
            ],
            options={
                'db_table': 'apartment_info',
                'managed': True,
            },
        ),
    ]
