# Generated by Django 4.0.1 on 2024-08-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalfilter',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
