# Generated by Django 4.0.1 on 2024-08-08 19:48

from django.db import migrations
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentinfo',
            name='end_date',
            field=web.models.StringDateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='valid_from',
            field=web.models.StringDateField(blank=True, default=None, null=True),
        ),
    ]
