# Generated by Django 4.0.1 on 2024-08-11 10:57

from django.db import migrations
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalfilter',
            name='credit_start',
            field=web.models.StringDateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personalfilter',
            name='update_time',
            field=web.models.StringDateTimeFieldUTC(auto_now=True, null=True),
        ),
    ]
