# Generated by Django 4.0.1 on 2025-04-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_personalfilter_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentstatus',
            name='valid_from',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
