# Generated by Django 4.0.1 on 2024-08-08 22:19

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_apartmentinfo_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentStatus',
            fields=[
                ('_id', web.models.ObjectIdField(default=None, max_length=24, primary_key=True, serialize=False)),
                ('update_time', web.models.StringDateTimeField(blank=True, default=None, null=True)),
                ('object_number', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('queue_len', models.IntegerField(blank=True, default=None, null=True)),
                ('most_credit', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'apartment_status',
                'managed': True,
            },
        ),
    ]
