# Generated by Django 4.0.1 on 2024-08-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_personalfilter_credit_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentinfo',
            name='floor',
        ),
    ]
