# Generated by Django 4.0.1 on 2024-08-10 20:45

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_apartmentstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalFilter',
            fields=[
                ('_id', web.models.ObjectIdField(default=None, max_length=24, primary_key=True, serialize=False)),
                ('update_time', web.models.StringDateTimeFieldUTC(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('regions', models.JSONField(blank=True, default=None, null=True)),
                ('types', models.JSONField(blank=True, default=None, null=True)),
                ('living_space', models.JSONField(blank=True, default=None, null=True)),
                ('rent', models.JSONField(blank=True, default=None, null=True)),
                ('floor', models.JSONField(blank=True, default=None, null=True)),
                ('short_rent', models.BooleanField(default=False)),
                ('electricity_include', models.BooleanField(default=False)),
                ('rent_free_june_and_july', models.BooleanField(default=False)),
                ('max_4_years', models.BooleanField(default=False)),
                ('current_credit', models.FloatField(default=100000.0)),
                ('credit_start', models.DateTimeField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'personal_filter',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='apartmentamount',
            name='update_time',
            field=web.models.StringDateTimeFieldUTC(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='update_time',
            field=web.models.StringDateTimeFieldUTC(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentstatus',
            name='update_time',
            field=web.models.StringDateTimeFieldUTC(blank=True, default=None, null=True),
        ),
    ]
