# Generated by Django 4.0.1 on 2024-08-11 10:48

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_personalfilter_alter_apartmentamount_update_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentinfo',
            name='update_time',
            field=web.models.StringDateTimeFieldUTC(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalfilter',
            name='electricity_include',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='personalfilter',
            name='floor',
            field=web.models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personalfilter',
            name='living_space',
            field=web.models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personalfilter',
            name='max_4_years',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='personalfilter',
            name='regions',
            field=web.models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personalfilter',
            name='rent',
            field=web.models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personalfilter',
            name='rent_free_june_and_july',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='personalfilter',
            name='short_rent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='personalfilter',
            name='types',
            field=web.models.JSONField(blank=True, default=None, null=True),
        ),
    ]
